{% set name = "astroedu" %}
{% set version = "0.4.3a0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astroedu-{{ version }}.tar.gz
  sha256: fe28c9675afe6aab21be8023507b649af0c0ce753d7fca865faed6089a4e6a74

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points: 
    - astroedu = astroedu.__main__:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - fire >=0.4.0
    - importlib-resources >=5.1.2
    - ipywidgets >=7.6.0
    - jupyterlab >=3.0.0
    - matplotlib-base >=3.3.0
    - numpy >=1.20.0
    - pandas >=1.1
    - python >=3.7
    - scipy >=1.6.0

test:
  imports:
    - astroedu
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/astroDimitrios/astroedu
  summary: A python package for astronomy educators
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astroDimitrios
